---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      volumes:
      - name: db-volume
        persistentVolumeClaim:
        claimName: prod-mysql-pv-claim
