---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
spec:
  template:
    spec:
      volumes:
      - name: db-volume
        persistentVolumeClaim:
        claimName: dev-mysql-pv-claim
