services:

  wiremock:
    container_name: "quotes-provider"
    image: "quay.io/rdacosta/wiremock:latest"
    volumes:
      - ~/ocp-apps/compose/wiremock/stubs:/home/wiremock:Z
    networks:
      - app-net

  quotes-api:
    container_name: "quotes-api"
    image: "quay.io/rdacosta/quotes-api:latest"
    ports:
      - "8080:8080"
    networks:
      - app-net
    environment:
      QUOTES_SERVICE: "http://quotes-provider:8080"

  quotes-ui:
    container_name: "quotes-ui"
    image: "quay.io/rdacosta/quotes-ui:latest"
    ports:
      - "3000:8080"

networks:
  app-net: {}
